### ISSUE TITLE
camelCase

### ISSUE THREAD

**Issue by IuriiPastushenko** [AyubTouba/nestjs-dbvalidator#22]
Youba!
There is an error in your module if we use camelCase: @Validate(IsUnique, [{ table: 'customers', column: 'carName' }]). 
As example, 
 query: "select carName from customers where  carName like 'Scoda1'   ",
 parameters: undefined,
 driverError: error: column "carname" does not exist

**Comment by AyubTouba** [comment]
@IuriiPastushenko thanks for sharing the bug here, don't hesitate if you have any other suggestion or question
